// Generated by ChatGPT

fetch('navbar.html')
    .then(res => {
        if (!res.ok) {
            throw new Error('Failed to fetch navbar.html');
        }
        return res.text();
    })
    .then(text => {
        const navbarScript = document.querySelector("script#navbar");

        // Get the current page's path
        const currentPage = window.location.pathname.split('/').pop().split('?')[0].split('#')[0];

        // If the current page is the root ("/"), treat it as "index.html"
        const pageToHighlight = (currentPage === '') ? 'index.html' : currentPage;

        // Replace script with navbar content
        const wrapper = document.createElement('nav');
        wrapper.innerHTML = text;

        // Highlight active link
        const links = wrapper.querySelectorAll('a');
        links.forEach(link => {
            if (link.getAttribute('href') === pageToHighlight) {
                link.classList.add('active');
            }
        });

        navbarScript.replaceWith(wrapper);
    })
    .catch(error => {
        console.error('Error loading navbar:', error);
        const fallbackElem = document.createElement('div');
        fallbackElem.innerHTML = '<p>Navigation menu could not be loaded.</p>';
        document.querySelector("script#navbar").replaceWith(fallbackElem);
    });